[Authentication]
ConsumerKey = ""
ConsumerSecret = ""
AccessToken = ""
AccessSecret = ""

[StreamFilterParams]
Track = [ "Golang" ]

[Source]
Whitelist = [ "Twitter for iPhone", "Twitter for Android" ]
